spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database: h2
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      SQL: DEBUG