spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
  h2:
    console:
      enabled: true
